<log>
  <summary_ verdicts='3' failures='2' errors='0'/>
  <section_ name='Test' method='verdict_assert_in_delta?' type='fail'>
    <section_ name='Args=[0, 2, 1, &quot;Message 0&quot;]'>
      <verdict_ method='verdict_assert_in_delta?' outcome='failed' id='0' message='Message 0'>
        <expected_ class='Integer' value='0'/>
        <actual_ class='Integer' value='2'/>
        <delta_ class='Integer' value='1'/>
        <exception_ class='Minitest::Assertion' message='Expected |0 - 2| (2) to be &lt;= 1.'>
          <backtrace_>
          </backtrace_>
        </exception_>
      </verdict_>
    </section_>
    <section_ name='Args=[2, 0, 1, &quot;Message 1&quot;]'>
      <verdict_ method='verdict_assert_in_delta?' outcome='failed' id='1' message='Message 1'>
        <expected_ class='Integer' value='2'/>
        <actual_ class='Integer' value='0'/>
        <delta_ class='Integer' value='1'/>
        <exception_ class='Minitest::Assertion' message='Expected |2 - 0| (2) to be &lt;= 1.'>
          <backtrace_>
          </backtrace_>
        </exception_>
      </verdict_>
    </section_>
  </section_>
  <verdict_ method='verdict_assert_equal?' outcome='passed' id='error_count'>
    <expected_ class='Integer' value='0'/>
    <actual_ class='Integer' value='0'/>
  </verdict_>
</log>
