<log>
  <summary verdicts='2' failures='2' errors='0'/>
  <section name='Test' method='verdict_assert_in_delta?' type='fail'>
    <section name='Args=[0, 2, 1]'>
      <verdict method='verdict_assert_in_delta?' outcome='failed' id='0' message='Message 0'>
        <expected class='Integer' value='0'/>
        <actual class='Integer' value='2'/>
        <delta class='Integer' value='1'/>
        <exception class='Minitest::Assertion' message='Expected |0 - 2| (2) to be &lt;= 1.'>
          <backtrace/>
        </exception>
      </verdict>
    </section>
    <section name='Args=[2, 0, 1]'>
      <verdict method='verdict_assert_in_delta?' outcome='failed' id='1' message='Message 1'>
        <expected class='Integer' value='2'/>
        <actual class='Integer' value='0'/>
        <delta class='Integer' value='1'/>
        <exception class='Minitest::Assertion' message='Expected |2 - 0| (2) to be &lt;= 1.'>
          <backtrace/>
        </exception>
      </verdict>
    </section>
  </section>
</log>
